### ISSUE TITLE
Enable incremental collection if parallel marker

### ISSUE THREAD

**Issue by lokeshgidra** [ivmai/bdwgc#151]
I wan to run GC in incremental mode. The  gc.h file in source code says that it doesn't work multi-threaded. So do I need to set both GC_MARKERS and GC_NPROCS to 1? Also, what is the difference between GC_MARKERS and GC_NPROCS?

**Comment by lokeshgidra** [comment]
Only setting GC_ENABLE_INCREMENTAL to 1 doesn't seem to work, if compiled with PARALLEL_MARK. In this case, GC_NPROCS or GC_MARKERS also needs to be set to 1, which results in GC_parallel being set to 0, for the incremental mode to be enabled. Is my understanding correct?

**Comment by ivmai** [comment]
GC_NPROCS is number of available CPU cores, GC_MARKERS is the number of parallel marker threads. Unless explicitly set, GC_MARKERS == GC_NPROCS.
True incremental collection is disabled if there are parallel marker threads. Incremental collection is considered to add more overhead than reduce stop-the-world pauses in case of several markers are running simultaneously. (It might worth to recheck it on modern H/W.)

**Comment by ivmai** [comment]
TODO:
* check whether true incremental collection is compatible with parallel marker
* if yes, measure if there is some performance benefit of true incremental collection on a dual core host

**Comment by ivmai** [comment]
To @hboehm : why do we disable true incremental collection in case of parallel marker on?
"If GC_parallel is set, incremental collection is only partially functional, and may not be desirable." (added to gc.h in gc v6.0 - 9f27ae7)

**Comment by hboehm** [comment]
Incremental GC normally does a very small amount of marking at a time in
response to some allocations. It would be tricky, and probably ineffective,
to start up a parallel GC phase, of the kind we use now, for that small
amount of collection. There is a comment in GC_mark_some describing this
problem. Currently, I think
we just end up running much of the marker non-incrementally.

IIRC, this isn't a very fundamental restriction. It would probably be
possible to restructure things so that multiple mutator threads can
concurrently run small pieces of the marking task during allocation, and we
can switch to the parallel work-sharing approach during the final
stop-the-world-gc. But we never got around to implementing that. Note that
normal incremental marking uses a single mark stack, and there may be other
work required to let those proceed in parallel.

**Comment by ivmai** [comment]
The issue is still open because it is unclear if there any benefit of the proposed commits.

**Comment by ivmai** [comment]
The issue is still open because it is unclear if there any benefit of the proposed commits.
