### ISSUE TITLE
about Android bdwgc, jemalloc, and c11 or c+14 thread and atomic library

### ISSUE THREAD

**Issue by radxe** [ivmai/bdwgc#170]
Hello, I am new about bdwgc,   
       1 there are bdwgc for android clang?
       2 can bdwgc using jemalloc or tcmalloc machinism? fast and little memory fragmentation.
       3 can bdwgc use c11 or c+14 thread and atomic library? so bdwgc use not asm code?

Thanks!

**Comment by ivmai** [comment]
1. While I used bdwgc from master branch, I'd recommend to use https://github.com/Unity-Technologies/bdwgc for now (it contains some Android-specific not integrated upstream yet)

2. bdwgc uses mmap or sbrk on Unix platforms by default, but it can use a custom method to get heap memory from the OS. I doubt there's any benefit of using jemalloc or tcmalloc as bdwgc grabs big page-aligned chunks from OS.

3. [libatomic_ops v7.6](https://github.com/ivmai/libatomic_ops/releases/download/v7.6.0/libatomic_ops-7.6.0.tar.gz) uses gcc atomic intrinsics, so if you configure bdwgc to use this libatomic_ops then no asm could should be used. (bdwgc master branch already uses gcc atomic intrinsics directly; there is a plan to switch to c11 atomic primitives this year.)

PS. It is better to ask questions at Stackoverflow - https://stackoverflow.com/questions/tagged/boehm-gc

**Comment by ivmai** [comment]
Hmm. It turns out that porting bdwgc to use C11 atomics instead of gcc is quite hard. The reason is: C11 Atomic<t> is not the same t (unlike libatomic_ops or GCC/Clang intrisics). The following scenario is quite typical in bdwgc:

void **p;
....
AO_CAS((volatile AO_t *)p, (AO_t)..,, (AO_t)...)
...
p2 = *p;

Of course, the stdatomic.h implementation I've looked at uses typedef struct { t } AO_t, so it is possible to add necessary casts between AO_t and t to bdwgc to enable C11 atomics but this is not portable (and looks complicated).

So, I think it does not worth to port bdwgc to C11 atomics and it does not give any visible benefit over the current implementation when GCC or Clang is used.

**Comment by ivmai** [comment]
Comment from @hboehm (about use of C11 atomics):
typedef _Atomic(GC_word) AO_t; - could probably be made to work, but I agree it's more work.
