### ISSUE TITLE
public symbol removed between 7.6.4 and 7.6.8

### ISSUE THREAD

**Issue by wookey** [ivmai/bdwgc#243]
Issue 241 said: "I'd also recommend you to ask debian guys to upgrade libgc to 7.6.8."

OK, I just had a go at this to see if it was easy, and it mostly is, but there seems to be an API change: these two symbols have gone: 
#MISSING: 1:7.6.8-1# GC_start_debugging@Base 1:7.2d
#MISSING: 1:7.6.8-1# GC_store_debug_info@Base 1:7.2d

(due to change in dbg_mlc.c)
GC_INNER ptr_t GC_store_debug_info(ptr_t p, word sz, const char *string,
                                   int linenum)
->
static void *store_debug_info(void *p, size_t lb,
                              const char *fn, GC_EXTRA_PARAMS)

Public symbols should not normally disappear from a library (because things which use it can break when it is upgraded). Can you explain what's going on here?  Was this symbol in fact one that was never used in the real world so this API change will not break anything? I'll send what I've done to the maintainer, but this change makes me a little  nervous about recommending such a change just before a stable release. Are there any other non-backwards-compatible API or ABI changes?

**Comment by ivmai** [comment]
> Public symbols should not normally disappear from a library (because things which use it can break when it is upgraded).

Yes, correct. 

> Can you explain what's going on here?

Both symbols (GC_start_debugging, GC_store_debug_info) have never been public officially, they just happened to be exported (because ELF exports everything unless hidden). Only the symbols that are marked with GC_API are considered to be public.

Both symbols were removed in bug-fix commit d6ccabe (all uses of GC_start_debugging was replaced with GC_start_debugging_inner which does not acquire the lock, the prototype of GC_store_debug_info was changed to accept other parameters). Technically it would be possible to resurrect the symbols (and make them public) if there any clients.

Note also that exportability of such non-public symbols depends on the build configuration, e.g. the mentioned 2 symbols are not exported even in v7.6.4 if you pass --disable-static to configure.

> Was this symbol in fact one that was never used in the real world so this API change will not break anything? 

Some gc symbols are marked with GC_API_PRIV meaning that they are not public yet they are exported because some known clients use them.
I haven't seen any information that someone uses the mentioned 2 symbols.

> Are there any other non-backwards-compatible API or ABI changes?

As you said the public symbols should not normally disappear from a library. I, as the maintainer, check the patches not to break the backward compatibility.
BTW. There's an external tracker of the API/ABI changes in libgc: https://abi-laboratory.pro/?view=timeline&l=bdwgc

**Comment by ivmai** [comment]
So, to sum up my opinion that it would be painless to drop these 2 symbols.
