### ISSUE TITLE
gc_cpp.h:545: undefined reference to GC_throw_bad_alloc()

### ISSUE THREAD

**Issue by trofi** [ivmai/bdwgc#268]
Hello!

In https://bugs.gentoo.org/679834 we discovered that `bdwgc-8` now inserts `GC_throw_bad_alloc` when `gc_cpp.h` is used. Probably intentional effect of https://github.com/ivmai/bdwgc/commit/2ce94e20e884063240e70f21e706d73b8281f604 

As I understand nix uses bdwgc only for strings allocated by expression evaluator (but not the rest of runtime):
    https://github.com/NixOS/nix/blob/2.0.4/src/libexpr/eval.cc#L19

`GC_throw_bad_alloc` is defined in `libgccpp.so` and is brought in by `GC_malloc(n);`. Is it an expected change?

What should such clients do? Is linking in `-lgccpp` a safe thing or it will change semantics of already present new/delete?

Thanks!

**Comment by ivmai** [comment]
Yes, this is known. Previously the fact that GC_malloc could fail was ignored (operator new returned nullptr in case of GC_malloc failure which was not compiled with the standard behavior of operator new).
Now, in v8.0.2+ (as well as in v7.6.8+), C++ GC allocators and gc_cpp operator new never return nullptr (they throw bad_alloc() instead).

Unfortunately, it is not possible to implement GC_throw_bad_alloc function (which just throws std::bad_alloc) in gc_cpp.h.

Such clients should have -lgccpp flag (i.e. depend on libgccpp package).
It should be safe to add this flag, I don't see any negative effect (except for a need to add a dependency on libgccpp package).

Actually, even before the mentioned change such clients had to link with libgccpp on Win32 platform (because new and delete operators are defined in gc_cpp.cc in case of MS VC++ compiler).

**Comment by trofi** [comment]
Makes sense. Thank you!

**Comment by dimpase** [comment]
Documentation on this could be clearer. At the moment from reading https://github.com/ivmai/bdwgc/blob/master/include/gc_cpp.h one might get at impression that linking against `-lgccpp` will change the semantics of `::new` for some classes, cf.
https://github.com/ivmai/bdwgc/blob/master/doc/gcinterface.md#L208

    Linking against libgccpp in addition to the gc library overrides ::new (and friends) to allocate traceable 
    memory but uncollectible memory, making it safe to refer to collectible objects from the resulting 
    memory.

(also, `traceable memory but uncollectible memory` above is just plain broken English)

**Comment by ivmai** [comment]
Thank you, I'll fix it

**Comment by dimpase** [comment]
It would be great if details on which `::new` comes from which library are spelled out.

Namely, my understanding is that `::new (NoGC)` comes from lib(std)c++, not from libgccpp, and it is not clear what happens with `::new` for classes that do not derive from the `gc` class.

**Comment by ivmai** [comment]
Now I understand what's wrong. GC_throw_bad_alloc() should be moved out of gc_cpp.cc but it is not clear where it should be placed.

**Comment by ivmai** [comment]
As now specified in gcinterface.md (added in commit 803f7ed):

If the user includes `gc_cpp.h` but `::new` should not be overridden then `libgctba` (in addition to the `gc`) library should be linked with to provide the definition of `GC_throw_bad_alloc` C++ function used by operator `new` of class `gc`.
Alternatively, the client may define `GC_NEW_ABORTS_ON_OOM` macro before include of `gc_cpp.h` (this instructs `::new` to issue an abort instead of throwing an exception), or may define `GC_INCLUDE_NEW` one before include of `gc_cpp.h` (however, this might not compile or work as expected on some platforms).

**Comment by ivmai** [comment]
Portable clients should now use -lgctba if use of -lgccpp is not acceptable.
