### ISSUE TITLE
maybe we need Better code directory organization?

### ISSUE THREAD

**Issue by sgf** [ivmai/bdwgc#315]
>[src]
>> [os]
>>> [win32]
>>> [unix]
>>> [macos]
>>> [symbian]
>>> [others...]

>> [gc]
>>> [core]
>>>[interfaces]
>>>>  [allocator]
>>>> [others...]

>> [api]
>>> [c]
>>> [cpp]
>> >[java]
>>> [others...]

**Among all the open source garbage collectors, this is a very good project and has a decisive position.**
It may be because the project supports a lot of OSs or platforms, and I just feel that there are too many files to start.maybe we need a better code directory organization?
The above is just an example. I don't know much about the project, so I can't sort out the structure of the project clearly.

**Comment by ivmai** [comment]
Probably. For a legacy multi-platform project, changing the structure is complicated. There should be a very good reason for the change.
E.g. once I had reorganized asm files but later I had to revert the change, see 5e756d4d8df

**Comment by ivmai** [comment]
One of the difficulty is that there are plenty of makefiles (for different platform), it is not feasible to check validity of them after folders reorganizations.

**Comment by ivmai** [comment]
But, of course, certain changes are possible, if needed.

E.g. one of things I'm thinking of is use of clang-format - to do this a configuration file should be created for clang-format. But the issue is: the configuration should maintain existing code style (i.e. `diff -w <before_change> <after_change> | wc -l` should be a low as possible ideally among all possible clang-format configuration). This requirement comes from the fact e.g. that further patches to master should be applicable to the code of old releases (before the reformatting). Unfortunately, I'm busy with other things(

**Comment by sgf** [comment]
Thanks, it has benefited me a lot.Such multi-dimensional project are quite complex.
