### ISSUE TITLE
Export CMake targets

### ISSUE THREAD

**Issue by SpaceIm** [ivmai/bdwgc#327]
In CMakeLists.txt, bdwgc defines `EXPORT` during targets installation:
https://github.com/ivmai/bdwgc/blob/ee900ca80085032156573517998c6cbfa1494377/CMakeLists.txt#L434
https://github.com/ivmai/bdwgc/blob/ee900ca80085032156573517998c6cbfa1494377/CMakeLists.txt#L456
https://github.com/ivmai/bdwgc/blob/ee900ca80085032156573517998c6cbfa1494377/CMakeLists.txt#L463

But actually, targets are never exported. Therefore bdwgc can't be consumed in CMake projects using `find_package`.

It would be nice to export (namespaced) targets and create a config file for CMake during installation.

**Comment by ivmai** [comment]
Hello @SpaceIm,

> It would be nice to export (namespaced) targets and create a config file for CMake during installation.

Could you please suggest the patch (at least draft)?

**Comment by SteveYoungs** [comment]
Hi @ivmai,

I should be able to devote some time to this over the weekend.  I'm pretty new to CMake, but I think this would be a reasonably straightforward thing to implement.

**Comment by SteveYoungs** [comment]
Hello @ivmai,

I now have a build here that is producing the necessary *.cmake files.  Another project could add bdwgc as one of their dependencies with something like this in their CMakeLists.txt...

```
find_package(BDWgc 8.1.0 REQUIRED)
add_executable(Foo foo.c)
target_link_libraries(Foo BDWgc::gc)
```
Or if they wanted to link against libgccpp they'd use...
`target_link_libraries(Foo BDWgc::gccpp)`

Before I send you a patch I have a couple of questions.  I've made it so that if a project wants to `target_link_libraries()` on libcord, libgccpp, or libgctba, they will automatically get libgc as well.  Is that the right way to go? Is there anything else along those lines that I should take into account?

**Comment by ivmai** [comment]
> I've made it so that if a project wants to target_link_libraries() on libcord, libgccpp, or libgctba, they will automatically get libgc as well. Is that the right way to go?

Yes, looks reasonable.

**Comment by ivmai** [comment]
Thank you. I've committed it with some modifications. Please test it (@SpaceIm and @SteveYoungs)
