### ISSUE TITLE
Licensing issue on de_win.rc

### ISSUE THREAD

**Issue by jengelh** [ivmai/bdwgc#331]
SUSE Legal has [identified](https://build.opensuse.org/request/show/811561) a problematic passage in de_win.rc:

```
License which does not allow modification found in
    cord/tests/de_win.rc
```

de_win.rc contains:

```
 * Permission is hereby granted to copy this garbage collector for any purpose,
 * provided the above notices are retained on all copies.
```

This is different from the rest of the source files which read

```
 * Permission is hereby granted to use or copy this program
 * for any purpose,  provided the above notices are retained on all copies.
 * Permission to modify the code and to distribute modified code is granted,
 * provided the above notices are retained, and a notice that the code was
 * modified is included with the above copyright notice.
```

**Comment by ivmai** [comment]
Also, gc_cpp.cc has same copyright text in de_win.rc.

I think this was not intentional, I will check it by looking into git log, and fix it.

**Comment by ivmai** [comment]
The following commands show the copyright when the files are first added:
git show gc4_1:cord/de_win.RC
git show gc4_8:gc_cpp.cc

The copyright message is the same as of now and it differs from that of other files in gc-4.1.

@hboehm, could you please comment on this issue?

**Comment by hboehm** [comment]
This was unintentional. If you look back at e.g. gc1.9 on the web site, you'll see that the only copyright notice is in the README file, and it matches the gc_cpp.cc notice. At some point, I learned that that notice was inadequate, and was instructed to change it to the current one. It looks like I missed two files. Especially  since the README file has contradicted this for about 25 years, please just go ahead and fix it.

I would be rather surprised if de_win.RC has any users. Gc_cpp.cc is arguably trivial, but perhaps more important.

**Comment by ivmai** [comment]
Fixed.
