### ISSUE TITLE
Build with Makefile.direct fails on FreeBSD

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#359]
source: latest master (b4f090726)
OS: freebsd12.1/x86_64
Build link: https://travis-ci.com/github/ivmai/bdwgc/jobs/516768512

make -f Makefile.direct check cord/de

cc   -O -I./include -I./libatomic_ops/src  -DALL_INTERIOR_POINTERS -DENABLE_DISCLAIM -DGC_ATOMIC_UNCOLLECTABLE  -DGC_GCJ_SUPPORT -DJAVA_FINALIZATION -DNO_EXECUTE_PERMISSION  -DUSE_MMAP -DUSE_MUNMAP   -c os_dep.c -o os_dep.o
os_dep.c:3258:19: error: use of undeclared identifier 'BUS_PAGE_FAULT'
    if (SIG_OK && CODE_OK) {
                  ^
os_dep.c:3215:42: note: expanded from macro 'CODE_OK'

**Comment by ivmai** [comment]
\+ @wangp

**Comment by wangp** [comment]
I did some investigating:

- The compilation error was revealed after this commit:
```
commit 65992c1476e9ba90bf165dff1340720c9e4f1268
Author: Ivan Maidanski <ivmai@mail.ru>
Date:   Wed Apr 10 23:33:39 2019 +0300

    Fix MPROTECT_VDB definition for single-threaded GC builds
    (fix of commit 6d9eec852)
    
    * include/private/gcconfig.h [MPROTECT_VDB && !MSWIN32 && !MSWINCE]:
    Include signal.h.
```
Prior to that, MPROTECT_VDB would be undefined when `<signal.h>` is not included, due to this:
```
#if defined(NO_SA_SIGACTION) && defined(MPROTECT_VDB) && !defined(DARWIN) \
    && !defined(MSWIN32) && !defined(MSWINCE)
# undef MPROTECT_VDB
#endif
```

- The compilation error also occurs with CMake if threads is disabled. With threads enabled, MPROTECT_VDB is not defined.

- The symbol `BUS_PAGE_FAULT` was removed between FreeBSD 11 and FreeBSD 12:
https://cgit.freebsd.org/src/commit/sys/x86/include/trap.h?id=d41e41f9f0ba9fdd2916584215b88ef7725280d7
I do not know what the "MI signal information" in that commit message refers to.
The `T_PAGEFLT` macro that `BUS_PAGE_FAULT` was aliased to still exists.

- `make check` does pass (on x86-64) if we simply delete the test against `BUS_PAGE_FAULT`, but I don't know if that means anything at all:
```diff
diff --git a/os_dep.c b/os_dep.c
index 23a83e45..d2be7930 100644
--- a/os_dep.c
+++ b/os_dep.c
@@ -3124,8 +3124,12 @@ GC_API GC_push_other_roots_proc GC_CALL GC_get_push_other_roots(void)
 #       define CODE_OK (si -> si_code == EXC_DSI \
                         || si -> si_code == SEGV_ACCERR)
 #     else
+#	ifdef BUS_PAGE_FAULT
 #       define CODE_OK (si -> si_code == BUS_PAGE_FAULT \
                         || si -> si_code == SEGV_ACCERR)
+#	else
+#       define CODE_OK (si -> si_code == SEGV_ACCERR)
+#	endif
 #     endif
 #   elif defined(OSF1)
 #     define CODE_OK (si -> si_code == 2 /* experimentally determined */)
```

**Comment by wangp** [comment]
Here are some threads relating to a transition from SIGBUS to SIGSEGV between FreeBSD 6 and FreeBSD 7:
https://fa.freebsd.current.narkive.com/8DAJ6wbW/serious-compatibility-breakage-in-current#post1
https://groups.google.com/g/comp.lang.lisp/c/KH0aVyJvDNo/m/wMQqj-N7i0sJ
https://lists.freebsd.org/pipermail/freebsd-hackers/2013-February/042057.html

**Comment by ivmai** [comment]
Got it. I'll make the patch.
But I will use __FreeBSD__ >= 7 instead of defined(BUS_PAGE_FAULT) because cppcheck does not like constructions like ifdef M ... use M's value

**Comment by ivmai** [comment]
Also, according to the links, powerpc does not need to check against EXC_DSI if \_\_FreeBSD\_\_ >= 7
