### ISSUE TITLE
clarify Java finalization doc?

### ISSUE THREAD

**Issue by hanwen** [ivmai/bdwgc#403]
finalization.md says

>Finalize.c actually contains an intentionally undocumented mechanism
 for registering a finalizable object with user-defined
 dependencies.  [..] The risk of dangling pointers can be eliminated by
 building the collector with -DJAVA_FINALIZATION. This forces objects
 reachable from finalizers to be marked, even though this dependency
 is not considered for finalization ordering.

I'm debugging a problem with Guile 2.2.6/Libgc 8.0.4, which I think
uses this undocumented mechanism, and is built with
-DJAVA_FINALIZATION. I'm wondering what "even though this dependency
is not considered for finalization ordering" means precisely.

We are seeing that even though Guile uses Java finalization, we
sometimes see an object's dependencies being finalized before the
object itself is finalized, which we thought Java finalization was supposed to 
prevent. More context in
https://lists.gnu.org/archive/html/guile-devel/2021-12/msg00005.html

Apologies in advance for asking for more documentation about an
intentionally undocumented mechanism.

**Comment by hboehm** [comment]
I believe that's expected behavior. It was required by Java's unordered
finalization.

I personally don't think this was a great language design decision, for
exactly the reasons you're running into,
and I'm not disappointed that Java has deprecated this style of
finalization in favor of java.lang.ref.
JAVA_FINALIZATION was implemented a long time ago to support gcj, where it
was required.
The GC's default topological ordering is normally preferable, if you don't
have to satisfy language spec
constraints to the contrary. Or you want something closer to
java.lang.ref.PhantomReference.)

**Comment by hanwen** [comment]
Let me check if I understand this: the Java finalization ensures that the GC won't deallocate/reuse the memory of the dependencies, so we can still look at the memory of the dependency object. However, the garbage collector doesn't attempt to enforce an ordering on how the finalizers are called? 

I think we are getting confused because, in our case, the finalization routines are used call deallocate memory under control of the C++ allocator. So the libGC-controlled bits are still there (no dangling pointer), but the C++ bits they point to are finalized (ie. deleted, in other words, dangling).

**Comment by hboehm** [comment]
On Fri, Dec 10, 2021 at 9:52 AM Han-Wen Nienhuys ***@***.***>
wrote:

> Let me check if I understand this: the Java finalization ensures that the
> GC won't deallocate/reuse the memory of the dependencies, so we can still
> look at the memory of the dependency object. However, the garbage collector
> doesn't attempt to enforce an ordering on how the finalizers are called?
>
> I think we are getting confused because, in our case, the finalization
> routines are used call deallocate memory under control of the C++
> allocator. So the libGC-controlled bits are still there (no dangling
> pointer), but the C++ bits they point to are finalized (ie. deleted, in
> other words, dangling).
>
Correct. This is exactly what happens in Java code if you have a Java
object that refers to a C++ object and use finalization to manage that. The
best practice there seems to be to have the finalizer clear any native
pointers (with suitable synchronization), and make the code as defensive as
possible against cleared C++ pointers. Is this a good idea? IMO, no. But
IIUC, that didn't prevent C# from copying it. So this odd behavior is
currently still mandated in some contexts. Java,lang.ref.Reference does not
have this behavior, since the "finalizer" does not have access to the
original object, which is clearly another way to approach this.

**Comment by hanwen** [comment]
thanks for the explanation. Now that I understand, the explanation in the .md file is quite clear, and we were just confused by having two layers of memory management and dangling pointers. 

I actually work on LilyPond which uses Guile (a Scheme interpreter), so we don't much choice in what libgc constructs we can use.

Thanks again for your response, I am honored to correspondend with Hans Boehm himself :-)
