### ISSUE TITLE
Crash on Android/arm if GC is a dynamic library

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#94]
Crash can be reproduced even on a simple console app which does GC_INIT + GC_malloc, GC is single-threaded. GC as a static library is ok. I haven't investigated the reason yet.

Target: android 6.x arm32
Source code: GC from master branch, libatomic_ops not used.

**Comment by manuel-serrano** [comment]
Dear Ivan,

The following might help you understanding the problem with Android.

I'm developing a large application that uses the collector extensively.
This application relies on multi-threading and dynamic loading. Many
people are using it on Linux boxes and MacOS. That application has been
used for years for realistic usages. It is considered as reliable.

Since a couple of weeks, I have been trying to port it to Android. I
have first tried the version 7.4.2. After struggling with tkill that
has been replaced with tgkill on recent Android versions (*) I have
been able to built it. Unfortunately, it was not working as after a
while the application crashed. Enlaring the initial heap size was
pushing back the crash, which sounds like a good indication that the
collector was broken. Using only static libraries did not help on that
matter.

I have then switched to the last git version of the collector but the
problem stays the same.

I have then modify the application source code to explictly register
all the global variables address as GC roots (using
GC_add_root). Apparently this solves the problem as the application
now seems okay (I have to be carefull as I have not yet conducted
thorough testing).

My hyphothesis is that on Android, the collector is not able to
correctly trace the global variables.

One way to investigate this issue could be to provide a tool (i.e., a GC
library predicate) that would tell if an address is already registered
as a root or not. It could be that this function already exist but I did
not find its description in gc.h. Provided with that function, I'm sure
I could help you fixing that problem we have.

--
Manuel


(*): I have not investigating much but it looks like the static and dynamic
versions of the Android C library do not export the same symbols!

**Comment by ivmai** [comment]
GC_INIT (which includes GC_add_root for data and bss) called from the client code should register apps static roots but it does not. Android is tricky and constantly changing. E.g. you might see a comment for GC_INIT_CONF_ROOTS.
Sorry, I don't have time currently for the investigation.

> One way to investigate this issue could be to provide a tool (i.e., a GC
library predicate)
I think it is possible to add such a predicate. 

For a discussion, it is better to use BDWGC mailing list.

**Comment by ivmai** [comment]
I think this is fixed in #259
